services:
  my-api:
    image: my-api:dev
    container_name: my-api_container
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - logs-data:/usr/src/app/logs
    networks:
      - super-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3333/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "npx prisma migrate deploy --schema=./prisma/schema && node main.js"
    depends_on:
      - redis
      - postgres

  next-app:
    image: next-app:dev
    container_name: next-app_container
    env_file:
      - .env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - super-network

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres_container
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      # These defaults ensure the container starts even if .env lookup fails
      POSTGRES_DB: ${DATABASE_DB:-my-db}
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-mypassword}
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - super-network
    volumes:
      # If POSTGRES_VOLUME_PATH is empty, it will create a folder called 'pgdata' in your current directory
      - ${POSTGRES_VOLUME_PATH:-./data}:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements

  redis:
    image: bitnami/redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis-data:/data
    networks:
      - super-network
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 500mb

  redis-commander:
    container_name: redis-commander_container
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    networks:
      - super-network
    depends_on:
      - redis

volumes:
  redis-data:
  logs-data:

networks:
  super-network:
    external: true
